services:
  mysql-reference-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql_ref_db"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    ports: [ "3306:3306" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 3s
      retries: 10

  postgres-reference-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres_ref_db"
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports: [ "5432:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10

