# only useful if source AND target are mysql
# this is the default mapping if "--config" is not used

# --- MySQL Sektion ---
[mysql.general]
# default behaviour for unknown types
on_missing_type = "warn" # oder "error"
#
default_charset = "utf8mb4"

[mysql.types.on_read]
# from mysql to internal representation (usually postgres)
"int" = "integer"
"timestamp" = "datetimetz"
"tinyint" = "smallint"
"mediumint" = "integer"
"double" = "double precision"
"tinytext" = "text"
"mediumtext" = "text"
"longtext" = "text"
"tinyblob" = "bytea"
"mediumblob" = "bytea"
"longblob" = "bytea"
"blob" = "bytea"
"binary" = "bytea"
"varbinary" = "bytea"
"datetime" = "timestamp"
"datetimetz" = "timestamptz"
"year" = "smallint"
"bit" = "bytea"
"enum" = "varchar"
"set" = "varchar"
"char" = "varchar"
"biginteger" = "bigint"

[mysql.rules.on_read]
unsigned_int_to_bigint = true
sql_mode = ""

[mysql.rules.on_write]
zero_date = true
sql_mode = ""

# --- Postgres Sektion ---
[postgres.types.on_read]
"cidr" = "inet"
"json" = "json"
"jsonb" = "json"

[postgres.types.on_write]
"json" = "jsonb"
"datetimetz" = "timestamptz"

[postgres.rules.on_read]

[postgres.rules.on_write]

# the end :-)

