[general]
# Standard-Verhalten für unbekannte Typen
on_missing_type = "warn" # oder "error"
default_charset = "utf8mb4"

[types]
# Explizite Typ-Konvertierungen
"tinyint(1)" = "boolean"
"datetime" = "datetime"
"timestamp" = "datetimetz"
"mediumtext" = "text"
"longtext" = "text"
"double" = "double precision"
# "blob"       = "bytea"
"blob" = "longblob"


[rules]
# Logikbasierte Regeln
# Konvertiert alle UNSIGNED INTEGER zu BIGINT in Postgres, da Postgres kein UNSIGNED unterstützt
unsigned_int_to_bigint = true

# Behandelt MySQL "0000-00-00" Datumsangaben
nullify_invalid_dates = true

[tables.column_overrides.users]
# Spezifische Spalten-Typänderungen in der Tabelle 'users'
"is_active" = "boolean"
"raw_data" = "jsonb"
