# --- MySQL Sektion ---
[mysql.general]
# default behaviour for unknown types
on_missing_type = "warn" # oder "error"
#
default_charset = "utf8mb4"

[mysql.types.on_read]
# from mysql to internal representation (usually postgres)
"integer" = "int"
"timestamp" = "datetimetz"

[mysql.types.on_write]
# from internal representation (usually postgres) to MySQL-Typ
"integer" = "int"
"datetimetz" = "timestamp"
"biginteger" = "bigint"
"text" = "longtext"
"blob" = "longblob"

[mysql.rules.on_read]
unsigned_int_to_bigint = true

[mysql.rules.on_write]
zero_date = true


# --- Postgres Sektion ---
[postgres.types.on_read]
"serial" = "int"
"timestamptz" = "datetimetz"

[postgres.types.on_write]
"int" = "serial"
"datetimetz" = "timestamptz"

